### ISSUE TITLE
stopResource introduces `size` argument - should update documentation

### ISSUE THREAD

**Issue by denis-tsoi-mox** [DataDog/dd-sdk-reactnative#133]
Ref:

https://github.com/DataDog/dd-sdk-reactnative/blob/ba2a6026a6394ba373c8f872aba2f6de68005362/packages/core/src/foundation.tsx#L74

The stopResource function was updated with the size parameter, which has not been updated in the documentation.
In the implementation details for swift/kotlin and native bridge reflect the updated argument.

---

Would like to get the authors comments on what size parameter does, I can add a PR for updating [documentation](https://github.com/DataDog/dd-sdk-reactnative/blob/fc103202010ef014d81519ea68ab90cadfb4ab29/README.md) and [tests](https://github.com/DataDog/dd-sdk-reactnative/blob/ba2a6026a6394ba373c8f872aba2f6de68005362/packages/core/src/__tests__/DdRumWrapper.test.tsx) afterward.

**Comment by denis-tsoi-mox** [comment]
If you can add a documentation label - that'd be great too. thx! 🙏

**Comment by 0xnm** [comment]
Hello @denis-tsoi-mox. Thanks for opening the issue! Indeed, it would be great, we appreciate external contributions.

This parameter describes the payload size (in bytes), as described in the [type definition](https://github.com/DataDog/dd-sdk-reactnative/blob/ba2a6026a6394ba373c8f872aba2f6de68005362/packages/core/src/types.tsx#L170).

In case of the React Native it is the size of inflated payload (if `gzip` is used, for example), because there is no way to access original (deflated) payload.
