### ISSUE TITLE
CodePush.restartApp not working after updating Datadog

### ISSUE THREAD

**Issue by tux4** [DataDog/dd-sdk-reactnative#215]
**Describe what happened**
After updating `@datadog/mobile-react-native` from `1.0.0-rc2` -> `1.0.0-rc8`, I am seeing a completely unrelated issue where my app doesn't restart when I call [`CodePush.restartApp` call](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-api-ref#codepushrestartapp) or try restarting the app in development by pressing `r` in the `metro` development console. 

**Steps to reproduce the issue:**

- Update `@datadog/mobie-react-native` -> `1.0.0-rc8`
- Press `r` in metro development console application, or call `CodePush.restartApp`
- Instead of restarting the app, it closes down without any warning or errors

**Describe what you expected:**

- The app restarts correctly as it did before.

**Additional context**
    - SDK Version: `1.0.0-rc8`
    - [package-copy.json.txt](https://github.com/DataDog/dd-sdk-reactnative/files/8861959/package-copy.json.txt)

Please let me know if you need any additional information. And thanks a lot for the help!

**Comment by louiszawadzki** [comment]
Hi @tux4, and thanks for opening this issue!

Could you share snippets from the files where you do initialize the Datadog SDK as well as CodePush?

Also I suggest a few debugging actions that might help pinpoint the issue:
- Does the issue happen on both iOS and Android?
- If you have native error tracking enabled, do you see any error in Datadog? 
- If you comment the Datadog initialization code (call to `DdSdkReactNative.initialize`), does the issue still happen?

Don't hesitate to come back to me if any of these isn't clear :)

**Comment by tux4** [comment]
Hi @louiszawadzki , 

Thanks for the prompt response and the suggestions for debugging. I am providing some additional information based on what you asked.

## Snippet

### CodePush initialization snippet

```
// This is exported from App.tsx which is the main App component

export default CodePush({
  checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME,
  installMode: CodePush.InstallMode.ON_NEXT_RESUME,
  deploymentKey: getCodePushDeploymentKey(),
})(Sentry.wrap(App));
```

### Datadog initialization snippet

```
// This is the main index.js file at the root of the app

const initializeDatadog = () => {
  const config = new DdSdkReactNativeConfiguration(
    Config.DATADOG_RUM_CLIENT_TOKEN,
    Config.ENV,
    Config.DATADOG_RUM_APPLICATION_ID,
    true, // track User interactions (e.g.: Tap on buttons)
    true, // track XHR Resources
    true, // track Errors
  );

  config.nativeCrashReportEnabled = true;

  DdSdkReactNative.initialize(config).catch(e =>
    logger.error('Datadog failed to initialize', e),
  );
};


AppRegistry.registerRunnable(appName, async props => {
  initializeDatadog();
  AppRegistry.registerComponent(appName, () => App);
  AppRegistry.runApplication(appName, props);
});

```

I tried the debugging steps you recommended and here is what I learnt.

> Does the issue happen on both iOS and Android?

Only happens in iOS. App is restarting correctly.

> If you have native error tracking enabled, do you see any error in Datadog?

I have attached the native error that was logged when the app crashes. Curiously, there is no mention of DataDog in the logs. Please find the attached log file for more.

[46a9ca6e40f643f5881f5becb87c6b75-symbolicated.crash.txt](https://github.com/DataDog/dd-sdk-reactnative/files/8864847/46a9ca6e40f643f5881f5becb87c6b75-symbolicated.crash.txt)

> If you comment the Datadog initialization code (call to DdSdkReactNative.initialize), does the issue still happen?


When I commend out the Datadog initialization code, the issue goes away, and the `CodePush.restartApp` call does what is expected.

Thanks again!

**Comment by tux4** [comment]
Hey @louiszawadzki ,

I am initializing Sentry in `App.tsx` outside of the component function like so -

```

const optionalSentryConfig: Sentry.ReactNativeOptions = {};
if (Config.RELEASE && Config.DIST) {
  optionalSentryConfig.release = Config.RELEASE;
  optionalSentryConfig.dist = Config.DIST;
}

Sentry.init({
  dsn: Config.SENTRY_DSN,
  environment: Config.ENV,
  ...optionalSentryConfig,
})
```

> In your index.js file, have you tried moving the Datadog initialization our of the registerRunnable, like so:

I tested by moving the `initializeDatadog` out of the `registerRunnable` but the behavior is the same as before, i.e. in iOS it is crashing instead of correctly restarting.

**Comment by louiszawadzki** [comment]
Hi @tux4 ,

I've reached out to our iOS SDK team to understand better what's going on here :) 
When looking at the crash log it seems that this line of code is breaking: https://github.com/getsentry/sentry-cocoa/blob/758519cbd4c38b8ee11927e11e005ad81b5f744d/Sources/Sentry/SentryNSURLSessionTaskSearch.m#L46

It *could* be because both the Sentry and the Datadog SDK swizzle (i.e. override the implementation) some of the `URLSession` APIs in Swift - we would need some time to make sure.

Now that bug probably happens only with version **1.0.0-rc8** because we've added support for first party hosts in this version. And on Datadog's iOS SDK, the moment we set first party hosts is also when we swizzle some of the `URLSession` APIs at the moment.

**What can be tried to prevent this bug**
- Using `codePush.restartApp` might lead to other issues with the native iOS SDK, such as actions, views and traces not being sent right after the reload - that will be fixed in the next release but in the meantime it might be worth disabling it if that's possible for you
- If you've added some `firstPartyHosts` in your configuration, try to remove them to see if this fixes the issue
  - On Datadog's iOS SDK side, we are going decouple the first party hosts and the swizzling some time in the future, which should enable you to specify `firstPartyHosts` once again if that was the cause of the issue
- Maybe look for a way to prevent the Sentry SDK from being initialized again when the packager reloads
- Finally, it may be worth to open an issue on Sentry's repo as well so they can look if they can also help preventing the crash 

Tell me if that makes sense, and if any of the suggestions worked!

**Comment by louiszawadzki** [comment]
Hi, 

We're aiming to release the new RC before the end of next week, it will contain the fixes for actions, views and traces not being sent right after a reload.
As for the initial issue, it looks like it is fixed on newer versions of Sentry (see the sentry issue thread) :) 

I've tested it to integrate both Sentry and Datadog and didn't have any crash on reload, let me know if that works for you as well :)

**Comment by tux4** [comment]
Hey @louiszawadzki,

After updating `"@sentry/react-native"` -> `"3.4.3"`, the crash went away. So it is all fine and good now. Thanks!

**Comment by louiszawadzki** [comment]
Hi @tux4 @milkman4, 
We've just released a new version which will ensure that actions, views and traces are being sent after a reload :)
