### ISSUE TITLE
use_frameworks! not supported

### ISSUE THREAD

**Issue by Kyonru** [DataDog/dd-sdk-reactnative#230]
Thanks for taking the time for reporting an issue!

**Describe what happened**
Can't perform `pod install`, datadog libraries throw an error.
<img width="803" alt="image" src="https://user-images.githubusercontent.com/17935828/179243013-7374ee7e-faaf-4b1d-95d8-9ac16aa6696e.png">
```
[!] The 'Pods-Redacted' target has transitive dependencies that include statically linked binaries: (DatadogSDKBridge and DatadogSDKCrashReporting)
Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: The 'Pods-Redacted' target has transitive dependencies that include statically linked binaries: (DatadogSDKBridge and DatadogSDKCrashReporting)
```

**Steps to reproduce the issue:**
- Add use_frameworks! to Podfile
- run pod install

**Describe what you expected:**

**Additional context**
- Version of the SDK
```
    "@datadog/mobile-react-native": "^1.0.0-rc8",
    "@datadog/mobile-react-navigation": "^1.0.0-rc8",
```

- A copy of your `package.json` file
```
    "react-native": "0.68.0",
```

**Comment by louiszawadzki** [comment]
Hi @Kyonru, thank you for reaching out!

To use our SDK with `use_frameworks!`, you need to add this snippet to your `Podfile`, inside the `target 'YourAppName' do` loop:

```ruby
  dynamic_frameworks = ['DatadogSDKBridge', 'DatadogCrashReporting']
  
  # Make all the other frameworks into static frameworks by overriding the static_framework? function to return true
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if !dynamic_frameworks.include?(pod.name)
        puts "Overriding the static_framework? method for #{pod.name}"
        def pod.static_framework?;
          true
        end
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end
```

**N.B:** If you already have a `pre_install` loop in your `Podfile`, add the content of this loop inside it instead of declaring a second loop, as only the last one in the file will be ran.

This comes from [this Stack Overflow answer](https://stackoverflow.com/questions/37388126/use-frameworks-for-only-some-pods-or-swift-pods/60914505#60914505).

Feel free to close this issue if that works for you :)

**Comment by Kyonru** [comment]
Thanks for the reply! It definitely work!
