### ISSUE TITLE
expo-datadog: iOS sourcemap upload incompatible with other plugins uploading sourcemaps

### ISSUE THREAD

**Issue by jackrr** [DataDog/dd-sdk-reactnative#291]
**Describe what happened**

1. Have an Expo project using [`expo-sentry` with source map uploads](https://docs.expo.dev/guides/using-sentry/#41-configure-a--postpublish--hook) and [EAS build](https://docs.expo.dev/build/introduction/)
2. Configure [Datadog RUM for Expo according to the docs](https://docs.datadoghq.com/real_user_monitoring/reactnative/expo/)
3. Run either a local or a remote EAS build `eas build --profile PROFILE --platform ios
4. Observe that the build fails with the following error:

```
/path/to/build/intermediates/.../APP_NAME.build/Script-00DD1BFF1BD5951E006B06BC.sh
error: Found argument 'datadog-ci' which wasn't expected, or isn't valid in this context
```
Inspecting the script contents, I find:
```
`node --print "require.resolve('@sentry/cli/package.json').slice(0, -13) + '/bin/sentry-cli'"` react-native xcode --force-foreground  yarn datadog-ci react-native xcode `node --print "require('path').dirname(require.resolve('react-native/package.json')) + '/scripts/react-native-xcode.sh'"`
```

**NOTE**: I've modified and omitted portions of the build output to preserve any proprietary information. I hope the rest of the bug report is sufficient to fill in the gaps.

I believe the issue [is rooted in this line](https://github.com/DataDog/dd-sdk-reactnative/blob/ff4a1efca4d6632b0785a9f9809b27abbdce6357/expo/src/plugin/withIosSourcemaps/withIosSourcemaps.ts#L22), where the source map ReactNative script is modified to include the `yarn datadog-ci react-native xcode` command.

If another package is also attempting to upload sourcemaps, this script gets appended to the end of that command, resulting in that upload command breaking, preventing the build from completing.

**Additional Context**
Relevant, filtered, `package.json` contents:

```
"dependencies": {
    "@datadog/mobile-react-native": "^1.1.1",
    "@datadog/mobile-react-navigation": "^1.1.1",
    "@expo/config": "~6.0.19",
    "@sentry/react-native": "^3.1.1",
    "expo": "^45.0.6",
    "expo-datadog": "^45.0.1",
    "expo-dev-client": "~1.0.1",
    "react": "17.0.2",
    "react-devtools-core": "^4.24.7",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-web": "0.17.7",
    "sentry-expo": "^4.2.0",
    "yarn": "^1.22.17"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@datadog/datadog-ci": "^1.14.2",
    "@expo/config-types": "^45.0.0",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.67.6",
    "typescript": "~4.3.5"
  },
```

**Comment by louiszawadzki** [comment]
Hi @jackrr, thanks for reaching out!

Indeed you spotted the right error. This is because both Sentry and Datadog config plugins edit the "Bundle React Native code and images" build phase in XCode using regexes, and it's hard to adapt to every case.
If you want to make it work, you can manually edit the build phase in your Xcode workspace (open it by running `xed ios` from your project) to look like so:

```
export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
export NODE_BINARY=node

# The project root by default is one level up from the ios directory
export PROJECT_ROOT="$PROJECT_DIR"/..

export SOURCEMAP_FILE="$DERIVED_FILE_DIR/main.jsbundle.map"
`node --print "require.resolve('@sentry/cli/package.json').slice(0, -13) + '/bin/sentry-cli'"` react-native xcode --force-foreground `node --print "require('path').dirname(require.resolve('react-native/package.json')) + '/scripts/react-native-xcode.sh'"`
yarn datadog-ci react-native xcode `node --print "require('path').dirname(require.resolve('react-native/package.json')) + '/scripts/react-native-xcode.sh'"`
```

What changes:
- `SOURCEMAP_FILE` now matches the `EXTRA_PACKAGER_ARGS` value
- It bundles the react-native code twice, first sending sourcemaps to Sentry, then to Datadog

Let me know if this works for you!

Supporting this use case properly needs a bit of work as there can be a lot of edge cases depending on the React Native and Sentry version, the order in which the plugins are applied, and maybe other factors. 
We've added this to our roadmap, but it's probably not going to be released soon, I'll let you know once this is released.

If you are seeing this issue and have the same problem, feel free to give it a 👍 to let us know that you're also willing to see it released :)

**Comment by bhyoo99** [comment]
@louiszawadzki
I'm having the same problem too.

I am also using Sentry, but in some parts, Datadog has strength, so we would like to use both.

Unfortunately, our team has built an internal app build workflow that does not edit the native layer directly, so we couldn't solve it with manual method suggested above.

If possible, please set this issue as a high priority
Thanks!
