### ISSUE TITLE
Upgrade source maps and bundle limit

### ISSUE THREAD

**Issue by AZagatti** [DataDog/dd-sdk-reactnative#302]
**Is your feature request related to a problem? Please describe.**
We are integrating the SDK into a large application, but I ran into the issue of the bundle and source maps upload limit, is there a mapping to increase this limit? Only the source maps today already gives the 50mb.

**Describe the solution you'd like**
Increasing the bundle and source maps upload limit, I believe 100mb would solve the problem for 99% of apps.

**Describe alternatives you've considered**
We are analyzing some things to reduce the size of the JS bundle, but today the heaviest is the source maps, if there is any way to reduce the size of it I would appreciate it.

**Additional context**

![android](https://user-images.githubusercontent.com/40201172/194396208-52ed7b98-bddc-4623-9b71-9a854b07130b.png)

![ios](https://user-images.githubusercontent.com/40201172/194402858-028355c7-8e2e-46ee-8e79-b6bca2b793a1.png)

![image](https://user-images.githubusercontent.com/40201172/194402984-482b0003-02f9-4577-b4b0-7aa9f4a5b647.png)

![image](https://user-images.githubusercontent.com/40201172/194403016-f4cf5dcb-da5b-4fc8-8dc0-09d9a9050bb9.png)

**Comment by louiszawadzki** [comment]
Hi @AZagatti, thanks for reaching out!

Unfortunately, we have no easy way of raising this limit for now. 

In the meantime, here are a few things you can try to thin your source maps as you are very close to the 50MB limit.

1. Remove the bundle from the upload - you will still be able to view your unminified sourcemaps. You can pass an empty file as argument to the upload command.
2. Analyse your bundle to find heavy or unused libraries - you can use a tool like https://github.com/IjzerenHein/react-native-bundle-visualizer. 
3. Use partial imports for heavy libraries - for instance importing `lodash/array` instead of `lodash`

If this did not enable you to get below 50MB, you can try to go further by splitting your bundle with repack: https://github.com/callstack/repack, then you can upload all your sourcemaps and bundles separately.

I hope this helps!

**Comment by louiszawadzki** [comment]
Hi again @AZagatti, one other thing that you can try is to remove the `"sourcesContent"` key of your source map file. 
We are going to soon add an option to `datadog-ci` to make it easier to do so as it can remove 2/3 of the total size.

The `"sourcesContent"` is used to display a code snippet next to the error to contextualize it a bit better. Without it you still get the unminified stacktrace.

**Comment by AZagatti** [comment]
Hi @louiszawadzki, is there an easy way to remove sourcesContent with rn cli? I created this command with perl (`perl -p -i -e 's/"sourcesContent".*"requireRefresh"],//g' ./android/build/index.android.bundle.map
`) to remove from the beginning of sourcesContent to the end that I found in my map, it worked to upload the source map but it gave a warning about 'git data', can you tell if there is a problem? I looked at the pointed position and it seems correct, but maybe there are some keys or brackets missing before.

![image](https://user-images.githubusercontent.com/40201172/194730076-2958354a-915f-44db-be7a-2c3c04803af5.png)

![image](https://user-images.githubusercontent.com/40201172/194730081-07028e40-1de8-4837-88de-dd38f8751cec.png)

I'll keep an eye on the new tracings that appear on the dashboard and see if it's working.

**Comment by louiszawadzki** [comment]
Hi @AZagatti, 

There is no current easy way to remove the sourcesContent with the CLI, it will come soon.

I used this node script to run a test (I did try it with a 30MB sourcemap file and had enough memory):

```javascript
fs = require('fs')
fs.readFile('./main.jsbundle.map', 'utf8', function (err,data) {
  if (err) {
    return console.log(err);
  }
  const sourcemap = JSON.parse(data);
  delete sourcemap.sourcesContent
  fs.writeFile('main.jsbundle.map.new', JSON.stringify(sourcemap), 'utf8' , function (err) {
    if (err) return console.log(err);
  ;})
});
```

**Comment by AZagatti** [comment]
Thanks @louiszawadzki, I put this node script in my script that generates and send source maps.

Any predictions for the release of the version with this script in datadog-cli?

**Comment by louiszawadzki** [comment]
Hi @AZagatti, 

We're having a deployment freeze until the end of next week as [Dash conference](https://www.dashcon.io/) is taking place.
It will probably be released in a new version at the end of next week. 

In the meantime, you can use the latest git version by specifying it like so in your `package.json` dependencies:

```
"@datadog/datadog-ci": "DataDog/datadog-ci#master"
```

**Comment by AZagatti** [comment]
Hi @louiszawadzki,

I managed to add this flow to our deploy pipeline by prefixing the codepush, but the code still doesn't appear correctly, can you tell me if I missed something?
I'll link some images:

![image](https://user-images.githubusercontent.com/40201172/200644523-fa37f82b-19d4-4f3a-8c70-f341d5c9823d.png)

![image](https://user-images.githubusercontent.com/40201172/200644847-dd166185-b21a-4752-b5c2-ebf61a5e8957.png)

**Comment by louiszawadzki** [comment]
Hi @AZagatti, 

Your errors are not being unminified on your 2 screenshots indeed.

About the first one, it is actually the android native crash that happens right after the javascript crash. 
Let me explain: when there is a fatal error in your javascript, we catch it and report it first on the javascript side. Then if your application crashes because of this error (which is the default behaviour for React Native apps), we also catch and report an error from the native side. This second error looks very similar to the javascript error, except its source is `android` (you can see the Android logo next to the error name) and the javascript stack is in plain text on the first line of the stack trace.

We know this is confusing and are sorry about this confusion, we're also planning to improve this very soon. In the meantime, you can disregard these errors.

About the second one, it would be expected to be unminified.
Just to make sure, did you send the correct source maps for the version we see here (`22.41.1-codepush.v1242`)?

If you indeed see the error with the minified stack trace in versions for which you've uploaded the source maps, we would need to look more into details of the sourcemaps you've uploaded. 
The best way to go would be for you to [contact our support](https://www.datadoghq.com/support/) so we can share information more easily. Please mention this issue when you contact our support so it can reach us quickly :) 

Thank you

**Comment by AZagatti** [comment]
Hi @louiszawadzki, sorry for the delay.

The logs are now improving in tracing, it must be something from the early versions.

The only thing that is showing up a lot of ANRException in Error Tracking, and in other services we don't have so many ANR reports, do you know if it happened to more people?

**Comment by AZagatti** [comment]
We've been using Sentry for some time, UXCam for some cases of sessions that also informs freezing and ANR and one of the main ones is Android Vitals that informs a very low amount of ANR, but I'll follow up and get in touch with anything, thank you @louiszawadzki!
