### ISSUE TITLE
Question: Minimum iOS platform

### ISSUE THREAD

**Issue by VincentCATILLON** [DataDog/dd-sdk-reactnative#31]
**Is your feature request related to a problem? Please describe.**

In our app, we are using 10 as minimum iOS version in our Podfile, but your bridge needs iOS 11 as minimum version.
If it's not required for your native SDK, can you downgrade to the minimum version you need (ie: 9 or 10) ?

> [!] The platform of the target `App` (iOS 10.0) may not be compatible with `DatadogSDK (1.5.1)` which has a minimum requirement of iOS 11.0.

**Describe the solution you'd like**

Being able to use the RN bridge with minimum version to 10.

**Additional context**

Version: `1.0.0-alpha3`

**Comment by priyanshi-gupta** [comment]
Hey @VincentCATILLON minimum supported version in the native-iOS SDK is iOS 11, since the react-native SDK is built upon the native-iOS bridge, it will not be possible to downgrade the version below iOS 11 without significant architectural changes.

**Comment by brian-visikon** [comment]
What a shame. 2% of our iOS users run on older versions, and we need data for all of our users for RUM to be considered an alternative to our current analytics platform.
Is there a pure javascript client we can use to manually post RUM entries from our react-native apps? We use the `@datadog/browser-rum` client in our normal react apps, but I expect that wont work in react native, because of instrumentation issues?
