### ISSUE TITLE
Enrich RUM events

### ISSUE THREAD

**Issue by Connor-Tang** [DataDog/dd-sdk-reactnative#364]
Context: we're using @datadog/mobile-react-navigation that automatically tracks views, and track XHR resources is enabled. Our backend service will respond with a special-Id on the response header, but the response header seems not being collected.

**Is your feature request related to a problem? Please describe.**
On RUM page, I'd like to add a new column for this special-Id, that it is collected as a response header only when the request fails.

Something like the `beforeSend` from `@datadog/browser-rum` described on this doc - https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm#identify-user-sessions

A function can be accepted as a part of config for the `DdSdkReactNative.initialize`, within the function, I can check the event type, response.statusCode, then add the response.headers to the context conditionally.

**Comment by louiszawadzki** [comment]
Hi @Connor-Tang, thanks for reaching out!

Adding event mappers is a popular demand and is high in our backlog!
I cannot give you a release date for it, but I'll link the PR to this issue once it's implemented and let you know when it is released :)

**Comment by LukasDzi** [comment]
Second this!

We are using GraphQL and default instrumentation is more or less useful as all requests goes to same domain.com/graphql endpoint. 

Are there other ways to customise resource tracking, e.g. not using default tracer?

**Comment by louiszawadzki** [comment]
Hi @Connor-Tang, 

Sorry for not coming back to you earlier, there is now a `resourceEventMapper` [parameter to the configuration](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/reactnative/#modify-or-drop-rum-events) that will enable you to edit the reported resource.
You should be able to access your header by calling [getResponseHeader](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getResponseHeader) on `resourceEvent.resourceContext`, where `resourceEvent` is the argument provided to the mapper.
This is available since version `1.3.0` of the SDK.

@lukas-dzikaras-tg you can now use [our dedicated Apollo GraphQL integration](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/integrated_libraries/?tab=kotlin#apollo-client) to display more information about your GraphQL requests since version `2.0.0` :) 

I'll close the issue, feel free to reopen it if you encounter any issue with
