### ISSUE TITLE
SDK Crash when creating initial config object

### ISSUE THREAD

**Issue by phillipkey** [DataDog/dd-sdk-reactnative#390]
Thanks for taking the time for reporting an issue!

If you are having trouble sending data from the SDK but don't see any error, please reach out first [through our support team](https://www.datadoghq.com/support/).

**Describe what happened**
App crashes on App start while trying to initialize the Datadog SDK with the following error:
<img width="329" alt="Screen Shot 2023-01-30 at 2 28 57 PM" src="https://user-images.githubusercontent.com/10274494/215610790-cc48a345-a1e1-458f-84ac-ab414b7837c2.png">

**Steps to reproduce the issue:**
Following the documentation for setup, the following configuration codeblock is called during the startup of the Root Application Controller
```   
const config = new DdSdkReactNativeConfiguration(
        "XXXXX",
        "beta",
        "XXXXX",
      )
await DdSdkReactNative.initialize(config)
```
**Describe what you expected:**
App should not crash on creating DdSdkReactNativeConfiguration object

**Additional context**

-   Version of the SDK - 1.2.1
-   React Native Version - 0.65.3

**Comment by louiszawadzki** [comment]
Hi @phillipkey, thanks for reaching out!

This looks like a typescript issue, the SDK will only work on Typescript version 4. 
If you are on an older version of typescript, can you try upgrading to at least version 4?

If you are already on version 4, could you share the content of the following files to help us troubleshoot:
- `tsconfig.json`
- `metro.config.js`
- `babel.config.js`

If you cannot upgrade to Typescript 4, you can alternatively tell metro to resolve the compiled version of the SDK instead of the Typescript version, by adding a [resolverRequest](https://facebook.github.io/metro/docs/configuration/#resolverequest) to your `metro.config.js` file:

```
module.exports = {
  resolver: {
    resolveRequest: (context, moduleName, platform) => {
      if (moduleName.startsWith('@datadog/mobile-react-native')) {
        return {
          filePath: `${process.cwd()}/node_modules/@datadog/mobile-react-native/lib/commonjs/index.js`,
          type: 'sourceFile',
        };
      }
      return context.resolveRequest(context, moduleName, platform);
    },
  },
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
};
```

**Comment by phillipkey** [comment]
@louiszawadzki thanks for the response! I will attempt to update it from `3.9.5` to `4.0.5` for now to do the smallest jump possible.

**Comment by phillipkey** [comment]
@louiszawadzki the SDK is no longer crashing. Thank you so much for your help!
