### ISSUE TITLE
React-native app crash on start after using startView() or addAction()

### ISSUE THREAD

**Issue by ayush6160** [DataDog/dd-sdk-reactnative#519]
**React-native app crashed whenever the addAction or startView function is used anywhere in the code**

- The app crashes on start and this error is logged on sentry (while using startView)
`ClassCastException: java.lang.Double cannot be cast to com.facebook.react.bridge.ReadableNativeMap`
- The app crashes on start and no error is logged (while using addAction)

**Steps to reproduce the issue:**

- import DdRum from the package `import { DdRum } from '@datadog/mobile-react-native';`
- Add the following code in the useEffect of the initial screen 

```
useEffect(() => {
    alert("Datadog started")
    DdRum.startView('ViewKey', 'ViewName', Date.now(), {
      'custom.foo': 'something'
    });
    DdRum.stopView('ViewKey', Date.now(), { 'custom.bar': 42 });
    alert("Datadog ended")
  }, []);

```

**Expected result:**

- Passed JSON to appear in datadog event tracking

**Comment by louiszawadzki** [comment]
Hi @ayush6160, thanks for reaching out!

The error message you logged indicates that you passed a number to a native module when it expected an object.
From the snippet you sent it looks like you indeed inverted the `context` (object) and `timestamp` (number) arguments to your `DdRum.startView` and `DdRum.stopView` calls, they should look like this instead:

```javascript
DdRum.startView(
  'ViewKey',
  'ViewName',
  {
    'custom.foo': 'something',
  },
  Date.now(),
);
DdRum.stopView('ViewKey', {'custom.bar': 42}, Date.now());
```

Making this change should fix your problem.

I'm closing the issue, please feel free to reopen it if your problem is not fixed :)
