### ISSUE TITLE
User is overwritten in session, when a different user, logs in on the same device

### ISSUE THREAD

**Issue by damianimashaun** [DataDog/dd-sdk-reactnative#53]
**Describe what happened**
Login as User A, [calls DdSdkReactNative.setUser({}) ]
Logout.
Login as User B, [calls DdSdkReactNative.setUser({}) ]

When I view the above session, all activity logged while User A was logged in, is kept in the same session as User B's activity.
**Steps to reproduce the issue:**
Login as a user A
Wait a few seconds/do a few things
Logout user A
Login as user B

check the logs
The entire session displayed, belongs to user B

**Describe what you expected:**
I expect a new session to be started when User B logs in (since SetUser is called, maybe check if another user is already assigned the session)

Is this standard behaviour ? 
Is there a workaround for this ?

**Additional context**
    - Version of the SDK: "1.0.0-beta1"
    - A copy of your `package.json` file

**Comment by xgouchet** [comment]
Hi @damianimashaun , 

this is indeed a standard behaviour. RUM Sessions are tied to the application's lifecycle since we can't know what counts as a user (as in individual user account) session in your application.
For now, session management is automated following some time limit rules, but we're thinking about letting you manually create a new session for this kind of use case. This has not yet been done simply because billing is based on the number of sessions, and this feature will increase your bill.

**Comment by damianimashaun** [comment]
thanks for clarifying @xgouchet 🙏🏾
