### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by oferRounds** [DataDog/dd-sdk-reactnative#539]
We’re in the process of migrating our react native app from using Firebase’s Crashlytics to DataDog. While testing it, we get the following crash:
<img width="1204" alt="image" src="https://github.com/DataDog/dd-sdk-reactnative/assets/1477963/355757f7-d281-474b-97f3-d4196a12dc76">
<img width="1252" alt="image" src="https://github.com/DataDog/dd-sdk-reactnative/assets/1477963/1dbe706a-15ea-46a5-b0da-7438ed60008c">

We don’t have a clear way to reproduce it. We use the latest datadog versions:

yarn.lock:
```
"@datadog/mobile-react-native-navigation@^1.5.2":
  version "1.8.5"

"@datadog/mobile-react-native@^1.5.2":
  version "1.8.5

"@datadog/datadog-ci@^2.10.0":
  version "2.22.1"
```

podfile.lock:
```
- DatadogSDK (1.22.0)
  - DatadogSDKCrashReporting (1.22.0):
    - DatadogSDK (= 1.22.0)
    - PLCrashReporter (~> 1.11.0)
  - DatadogSDKReactNative (1.8.5):
    - DatadogSDK (~> 1.22.0)
    - DatadogSDKCrashReporting (~> 1.22.0)
```
React native version: 0.71.12

Any idea? If that’s not enough, we can send you privately the files themseleves

**Comment by louiszawadzki** [comment]
Hi @oferRounds, thanks for reaching out!

From the error message, it looks like your app is having trouble to find the `DdLogsImplementation.swift` methods that are exposed to objective-c. 
This could be caused by an issue to compile the Swift file in the context of your app.

To help us troubleshoot, could you share the following information:
- are you using the React Native new architecture?
- are you calling `DdLogs.error` in your code? If so, what parameters do you pass?
- what are the values for `SWIFT_VERSION` and `SWIFT_OPTIMIZATION_LEVEL` in the XCode build settings for the scheme you're building? (you can also find this information in your `project.pbxproj` file)
- do you know of any special XCode build setting in your app?


This might be tricky to debug without access to the whole app, I encourage you to reach out to our support team (https://www.datadoghq.com/support/) mentioning this issue, this will be the best way to securely exchange files.

Thanks a lot!

**Comment by oferRounds** [comment]
Hey @louiszawadzki thank you for your fast reply!
As for your questions:
- We’re not using the architecture?
- We do use `DdLogs.error`: when we get a non-fatal error, we log it – passing one parameter of string-type error
- SWIFT_VERSION – 4.2 (for the app target; other target as values such as 4.1 and 5.0)
- SWIFT_OPTIMIZATION_LEVEL – "optimize for speed" (on release mode)
- Don’t know of any other special Xcode build settings, but I can send you the flle itself

Anyhow, I’ll also send it to the support

Thank you!

**Comment by louiszawadzki** [comment]
Hi @oferRounds, thanks for getting back quickly on this!

Unfortunately I'm not able to reproduce it so far with just changing the Swift parameters, so it could be something else.

I would still recommend you to set a `SWIFT_VERSION` of `5.0` if possible as it is the default version for RN 0.71 and the one we test the SDK against.

And to make sure the issue lies in the Swift file compilation, could you share the generated swift header file for the SDK?

To get it:
- open your project in xcode: `xed ios`
- select the file explorer and open "Pods" > "Development Pods" > "DatadogSDKReactNative" > "DdSdk" (the file with a "m+" blue icon, not the header file)
![image](https://github.com/DataDog/dd-sdk-reactnative/assets/8973379/677d2c3f-c549-4271-ba3f-85f249554dfe)

Here, command + click on the `#import <DatadogSDKReactNative-Swift.h>` and choose "Jump to Definition" (if it does not work, try for the `#import <DatadogSDKReactNative/DatadogSDKReactNative-Swift.h>` line).

You should see a file that starts by something like this:

```c
#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
#ifndef DATADOGSDKREACTNATIVE_SWIFT_H
#define DATADOGSDKREACTNATIVE_SWIFT_H
```

This file is quite long and does not contain any data specific to your app. If the Swift compilation fails for a reason, some methods definitions will be missing here - that's what I will be looking for.
If that's the case, we should be able to then find the reason for it by looking at your app's build logs.


Thanks a lot!

**Comment by oferRounds** [comment]
Hey @louiszawadzki 
 first of all, sorry for my delay!
 
 Few updates: it seems the original crash happens because we logged a non-fatal error before the sdk was initialized. But although fixing it on our side has mostly made the crash gone, it did not fix it completely. To fix it completely, we had to remove a 2 seconds timeout – starting after the initialization. Only after the time out passes we flag true the option to log the errors
 
 But – we still see some errors which seems related. Can you have a look here (an Android crash)?
 
<img width="1257" alt="image" src="https://github.com/DataDog/dd-sdk-reactnative/assets/1477963/ed63dc82-ef1a-441a-b095-a444f7797f00">

**Comment by louiszawadzki** [comment]
Hi @oferRounds,

From the error you shared it looks like you are trying to call `DdLogs.error` with a `message` parameter that is not of type string (either `null` or `undefined`).

Do you have a call to `DdLogs.error` in your codebase where the `message` param could potentially be `null` or `undefined`? 
If you are catching a JS Error somewhere, `error.message` can potentially be `null` or `undefined`.

**Comment by oferRounds** [comment]
ahmm I’ll check. But I think it worse also adding the protection on your side

**Comment by louiszawadzki** [comment]
Hi @oferRounds, 

Let me know if you found anything on your side. Otherwise I'd recommend you to reach out through [our support team](https://www.datadoghq.com/support/) so we can better assist you.

Adding a protection layer on our side is indeed in our backlog.
