### ISSUE TITLE
Missing data from Android RunTimeException crash

### ISSUE THREAD

**Issue by nys99** [DataDog/dd-sdk-reactnative#568]
**Describe what happened**

We have an expo app that is running on an ViewSonic Android tablet. Our app occasionally experiences a native `out of memory` exception: 

```
java.lang.RuntimeException: Error calling RCTDeviceEventEmitter.emit
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:164)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.OutOfMemoryError: std::bad_alloc
	... 7 more
```

By our estimates we are able to see the crash data reported in datadog about half the time, whereas in the other half we experience the crash but it does not show up in our datadog log data.

From what I understand, datadog writes log data to the `tmp` folder and periodically uploads the data to datadog. When a crash occurs the data is then uploaded the next time the app is restarted. 

Our current hypothesis is that the `Out of Memory` error is causing an error in which the crash data is not written to the `tmp` folder before the app crashes. However, this is just an assumption.

Are there steps we can take to better debug what is going on? Are there configurations that we can set that may help get to the bottom of the issue?

Any insight would be greatly appreciated!

**Steps to reproduce the issue:**

Cause an Java OutOfMemoryError when running a react native app. 

**Describe what you expected:**

All crashes should be uploaded to datadog

**Additional context**

-   Version of the SDK: 2.0.1
-   Version of React Native: 0.72.6
-   `package.json` 
-   `Podfile` and `Podfile.lock`
-   `android/build.gradle` and `android/app/build.gradle`

**Comment by louiszawadzki** [comment]
Hi @nys99, thanks for reaching out!

The OutOfMemory (OOM) situation is a very tricky one. If an OOM occurred, it means that the app tried to create an object and allocate memory, but couldn't do it. What this means is that when our SDK gets the information about the crash, it will try to write it to a local file, but because the memory is already full, there's a chance that the writing process will not work at all.

What I can recommend is to try to limit the footprint of the SDK as much as possible by setting these 2 settings in your SDK configuration:

```js
import {
  BatchSize,
  UploadFrequency,
} from "@datadog/mobile-react-native";

config.uploadFrequency = UploadFrequency.FREQUENT;
config.batchSize = BatchSize.SMALL;
```

Can you try this and report if that works better?

Also, I'm curious of how you get the crash information, is it by manually testing or through the Play Store?

**Comment by nys99** [comment]
Hi @louiszawadzki, thank you for the response! I will update our config with these settings and see if helps the issue.

The app in question is an internal app, so we are seeing the crashes reported by our internal users.

**Comment by louiszawadzki** [comment]
Hi @nys99,

There has not been any activity on this issue for a while so I'm going to close it.

Feel free to reopen it with more details if you still encounter the problem :)
