### ISSUE TITLE
Android Errors not visible on Track Errors tab 

### ISSUE THREAD

**Issue by consuelo-sanna** [DataDog/dd-sdk-reactnative#599]
**Describe what happened**
Good morning, I was able to connect DataDog with the React Native application and I can see the logs and traces, I'm now trying to test the crash reporting but there's something wrong

I can see the Errors in the **UX Monitoring -> RUM -> Session Explorer**  and clicking into one of the lines with the error counts, where there are the informations for both ios and android sessions

If I go to **UX Monitoring -> RUM -> Error Tracking**  though, I can only see the ios errors. 

Is this something to be expected? I noticed that RUM for react native does not support Frustrations or Replay yet so I've read that errors tracking were supported

**Steps to reproduce the issue:**
Follow the documentation on how to track errors and test them 
https://docs.datadoghq.com/real_user_monitoring/error_tracking

**Describe what you expected:**
I would expect the errors to show up in the Errors Tracking tab for Android

**Additional context**

-   Version of the SDK: 2.0.4
-   Version of React Native: 0.73.2

**Comment by louiszawadzki** [comment]
Hi @consuelo-sanna, thanks for reaching out!

Indeed errors should appear in both places. As errors are reported in RUM Sessions, the issue can come from a lot of different places of the Datadog platform or from your Datadog setup.

I recommend you to reach out to [our support team](https://www.datadoghq.com/support/) that will be more able to help you troubleshoot this issue.

I'll leave this issue open for a few days in case there are other reports of it. Feel free to close it if you managed to get it fixed with our support team!
