### ISSUE TITLE
Make context optional

### ISSUE THREAD

**Issue by tbeech** [DataDog/dd-sdk-reactnative#64]
**Is your feature request related to a problem? Please describe.**
Several methods such as DdRum.addAction(), DdLogs.debug|info|warn|trace() all take an additional context object, it would be nice if in cases where context is just empty, that this object is optional and that the implementation handles whether or not a default empty context is supplied.

**Describe the solution you'd like**
`DdRum.addAction('my_action', 'my_button', Date.getTime())`
`DdLogs.info('my info log')`

**Describe alternatives you've considered**
The alternative in this case is to supply a default empty object. This ultimately clutters up the code and makes it less clear as to it's purpose and intent.

`DdRum.addAction('my_action', 'my_button', Date.getTime(), {})`
`DdLogs.info('my info log', {})`

**Additional context**

**Comment by 0xnm** [comment]
Hello @tbeech! We've reworked API of our SDK and it is available now here https://www.npmjs.com/package/@datadog/mobile-react-native (if you were using `React Navigation` view tracking, it is available now in the dedicated package https://www.npmjs.com/package/@datadog/mobile-react-navigation). With that change you can now use optional arguments, so that any of the following is allowed:

```
DdRum.addAction('CUSTOM', 'foobar');
DdRum.addAction('CUSTOM', 'foobar', {'foo': 'bar'});
DdRum.addAction('CUSTOM', 'foobar', {'foo': 'bar'}, Date.now());
```

Please note that positions of the `context` and `timestamp` arguments are swapped in the new version of our SDK.
