### ISSUE TITLE
Android runtime error with v2.3.1

### ISSUE THREAD

**Issue by short-dsb** [DataDog/dd-sdk-reactnative#642]
### Describe the bug

Android build runs successfully with React Native v0.72.10, but has this runtime error:

> java.util.HashMap cannot be cast to com.facebook.react.bridge.ReadableMap

![error](https://github.com/DataDog/dd-sdk-reactnative/assets/105942728/4c4c420e-5000-46a5-9735-3585516950f6)

iOS is unaffected.

### Reproduction steps

1. `npm run android`

### Expected behavior

Android app runs successfully.

### Affected SDK versions

2.3.1

### Latest working SDK version

2.2.0

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Integration Methods

NPM

### React Native Version

0.72.10

**Comment by marco-saia-datadog** [comment]
Introduced with [https://github.com/DataDog/dd-sdk-reactnative/pull/625](https://github.com/DataDog/dd-sdk-reactnative/pull/625) (Native Initialization)

```kotlin
internal fun ReadableArray.asFirstPartyHosts(): Map<String, Set<TracingHeaderType>> {
    val firstPartyHosts = this.toArrayList() as List<ReadableMap>
    return firstPartyHosts.mapNotNull<ReadableMap, JSONFirstPartyHost> {
        val match = it.getString("match")
        val propagatorTypes = it.getArray("propagatorTypes")
        if (match != null && propagatorTypes != null) {
            JSONFirstPartyHost(match, propagatorTypes.toArrayList() as List<String>)
        } else null
    }.asFirstPartyHosts()
}
```

Based on the error, it seems that after calling `this.toArrayList()`, the array contains instances of HashMap(s) instead of ReadableMap(s), leading to a runtime error.

These are unchecked casts from List<Object>:

`this.toArrayList as List<ReadableMap>` 
`propagatorTypes.toArrayList() as List<String>`

Either the method `toArrayList` takes care of converting ReadableMap(s) to HashMap(s) already, or there is a particular scenario in which the original ReadableArray contains HashMap(s) instead of ReadableMap(s).

I am investigating.

EDIT:

It seems to be the case that ReadableNativeArray method `toArrayList()` converts Readable/Writable maps to HashMap(s):

```kotlin
public ArrayList<Object> toArrayList() {
    ArrayList<Object> arrayList = new ArrayList();

    for(int i = 0; i < this.size(); ++i) {
        switch (this.getType(i)) {
            case Map:
                arrayList.add(this.getMap(i).toHashMap());
                break;
    // ...
```

**Comment by jheurtin** [comment]
Hey, I am experiencing the same issue.
Is there a solution or a workaround please ?

**Comment by marco-saia-datadog** [comment]
Unfortunately the crash occurs on Android when setting `firstPartyHosts` in your configuration. We apologise for the inconvenience, you can either revert the version to 2.2.0 or follow the progress of this PR https://github.com/DataDog/dd-sdk-reactnative/pull/644 that will soon be contained in a new release.

**Comment by short-dsb** [comment]
Thanks for looking into this, @marco-saia-datadog.
