### ISSUE TITLE
[Feature Request] Be able to obtain trace propagation HTTP headers to manually propagate traces

### ISSUE THREAD

**Issue by JessicaYeh** [DataDog/dd-sdk-reactnative#83]
Hi team! My team has been using a custom built DataDog React Native module that bridges the iOS/Android SDKs and just has the bare functionality that we need while we waited for this official DataDog React Native SDK. One thing we need is to be able to distribute traces from frontend to backend, so we followed the docs here: https://github.com/DataDog/dd-sdk-ios/blob/master/docs/trace_collection.md (see number 8). For each HTTP request we make in RN (we're using Apollo client graphql) we called a RN bridge function that, on the native side, would first start the span and use that HTTPHeadersWriter (iOS) or HttpHeadersInjectAdapter (Android) to obtain the headers, important one being the trace ID, and we returned that to JS over the bridge so that we could set the `x-datadog-trace-id` header on each request in an Apollo link. Then the span is stopped at the end of the request.

I have been checking out the beta of this SDK to see if we can start using it and get rid of our custom bridge, but it seems like there isn't yet a way to be able to do this manual propagation of traces, so we'd like to request this feature for a future version of the SDK!

If this is already possible with the SDK and I missed something please let me know!

**Comment by 0xnm** [comment]
Hello @JessicaYeh. As of `1.0.0-beta3` we support traces propagation for XHR-based requests for the apps running on Android (not supported yet on iOS, but it will be there as well very soon). We didn't look into compatibility with [Apollo Client](https://www.apollographql.com/docs/react/) yet, but if it is using [XMLHttpRequest](https://reactnative.dev/docs/network) under the hood, then it will work (see [here](https://github.com/DataDog/dd-sdk-reactnative/blob/main/src/rum/instrumentation/DdRumResourceTracking.tsx) for the details). The only limitation is that network trace cannot be a continuation of existing trace, so network span will be at the root of the trace.

To make it work you need to explicitly enable resources tracking in the SDK configuration as stated [here](https://docs.datadoghq.com/real_user_monitoring/reactnative/#initialize-the-library-with-application-context).

Since you already have an existing app with custom wrapper, I would suggest you to check our [sample app](https://github.com/DataDog/dd-sdk-reactnative/tree/main/example) first: just put your credentials there and replace some URL with the URL of your backend to see how it works.

Let us know if existing functionality in our React Native SDK is enough or not for your needs.

**Comment by 0xnm** [comment]
Hello @JessicaYeh. We didn't hear from you back, so I hope solution above works for you and I'm closing the ticket. Feel free to re-open it if needed.

**Comment by ddeath** [comment]
Hi @0xnm,
I would like to see this feature also... One reason why we would need this is that there might be multiple libraries which are doing the same - overriding default behaviour of `XMLHttpRequest`
